version: "3.9"

services:
  mongo:
    image: mongo:6
    container_name: mern-mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: ./backend
    container_name: note-backend
    restart: always
    env_file:
      - ./.env.production
    ports:
      - "13035:5001"
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
    container_name: note-frontend
    restart: always
    env_file:
      - ./.env.production
    ports:
      - "13036:80"
    depends_on:
      - backend

volumes:
  mongo_data:
