

services:


  backend:
    build:
      context: ./backend
    container_name: note-backend
    restart: always
    env_file:
      - ./.env.production
    ports:
      - "13035:5001"
   

  frontend:
    build:
      context: ./frontend
    container_name: note-frontend
    restart: always
    env_file:
      - ./.env.production
    ports:
      - "13036:80"
    depends_on:
      - backend

volumes:
  mongo_data:
