name: CI/CD with Security Scan

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout (ให้ Sonar คำนวณ New Code ได้แม่น)
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2) Setup Node.js (รองรับ react-router@7 ที่ต้องการ Node >=20)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 3) Backend tests + coverage
      - name: Test backend (with coverage)
        run: |
          cd backend
          npm ci
          npm test -- --coverage --passWithNoTests

      # 4) Frontend tests + coverage (มี guard ถ้าไม่มี script test จะข้าม)
      - name: Test frontend (with coverage)
        if: hashFiles('frontend/package.json') != ''
        run: |
          cd frontend
          npm ci
          if npm run | grep -q "^  test"; then
            npm test -- --coverage --passWithNoTests
          else
            echo "No frontend test script. Skipping tests."
          fi

      # 5) npm audit (SCA)
      - name: Run npm audit
        run: |
          cd backend
          npm audit --audit-level=high

      # 6) SonarCloud Scan (CI-based)  ← อย่าลืมปิด Automatic Analysis ที่ SonarCloud
      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v6.0.0
        with:
          args: >
            -Dsonar.projectBaseDir=.
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # (ตัวเลือก) ล้ม pipeline หาก Quality Gate ไม่ผ่าน
      - name: Sonar Quality Gate
        uses: SonarSource/sonarqube-quality-gate-action@v1.1.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      # 7) Login Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 8) Build backend image
      - name: Build backend image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/note-backend:${{ github.sha }} ./backend

      # 9) Trivy scan backend image
      - name: Run Trivy on backend image
        uses: aquasecurity/trivy-action@0.13.1
        with:
          image-ref: ${{ secrets.DOCKER_USERNAME }}/note-backend:${{ github.sha }}
          format: 'table'
          exit-code: '1'
          severity: 'HIGH,CRITICAL'

      # 10) Push backend image
      - name: Push backend image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/note-backend:${{ github.sha }}

      # 11) Build frontend image (ถ้ามี Dockerfile)
      - name: Build frontend image
        if: hashFiles('frontend/Dockerfile') != ''
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/note-frontend:${{ github.sha }} ./frontend

      # 12) Trivy scan frontend image (ถ้ามี)
      - name: Run Trivy on frontend image
        if: hashFiles('frontend/Dockerfile') != ''
        uses: aquasecurity/trivy-action@0.13.1
        with:
          image-ref: ${{ secrets.DOCKER_USERNAME }}/note-frontend:${{ github.sha }}
          format: 'table'
          exit-code: '1'
          severity: 'HIGH,CRITICAL'

      # 13) Push frontend image (ถ้ามี)
      - name: Push frontend image
        if: hashFiles('frontend/Dockerfile') != ''
        run: docker push ${{ secrets.DOCKER_USERNAME }}/note-frontend:${{ github.sha }}

      # 14) Deploy to VM via SSH + docker compose
      - name: Deploy to VM
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            if [ ! -d "~/noteboard/.git" ]; then
              git clone https://github.com/<your-username>/mern-thinkboard.git ~/noteboard
            fi
            cd ~/noteboard
            git pull origin main
            export GITHUB_SHA=${{ github.sha }}
            docker compose -f docker-compose.prod.yml pull
            docker compose -f docker-compose.prod.yml up -d --remove-orphans

      # 15) Health check (เช็ก backend จริง: /api/health)
      - name: Health check backend
        run: |
          for i in {1..10}; do
            if curl -fsS http://57.155.0.49:13036/api/health > /dev/null; then
              echo "Backend healthy"
              exit 0
            fi
            echo "Waiting for backend..."
            sleep 5
          done
          echo "Backend NOT healthy"
          exit 1
