name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # Login Docker Hub
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Build & Push Backend
    - name: Build and push backend
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/note-backend:latest ./backend
        docker push ${{ secrets.DOCKER_USERNAME }}/note-backend:latest

    # Build & Push Frontend
    - name: Build and push frontend
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/note-frontend:latest ./frontend
        docker push ${{ secrets.DOCKER_USERNAME }}/note-frontend:latest

    # Deploy to VM
    - name: Deploy on VM
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.VM_HOST }}
        username: ${{ secrets.VM_USER }}
        key: ${{ secrets.VM_SSH_KEY }}
        script: |
          cd ~/noteboard
          git pull origin main || true
          docker compose -f docker-compose.prod.yml pull
          docker compose -f docker-compose.prod.yml up -d
